//! M0 method catalog (MASTER 4.2 reference; this crate is the authority).

use crate::{Capability, Idempotency, MethodSpec, SideEffect, Undo};
use gs_protocol::APP_CODE_PROTO;

const E_VALIDATION: &str = "E_VALIDATION";
const E_NOT_FOUND: &str = "E_NOT_FOUND";
const E_CONFLICT: &str = "E_CONFLICT";
const E_LOCKED: &str = "E_LOCKED";
const E_PAUSED: &str = "E_PAUSED";
const E_BUDGET: &str = "E_BUDGET";
const E_PROJECT_OPEN: &str = "E_PROJECT_OPEN";
const E_UNAUTHORIZED: &str = "E_UNAUTHORIZED";
const E_PATH: &str = "E_PATH";

const EVENT_SCENE_CHANGED: &str = "event.scene_changed";
const EVENT_SESSION_CHANGED: &str = "event.session_changed";
const EVENT_CONFIRMATION_REQUEST: &str = "confirmation.request";
const EVENT_PLAY_CHANGED: &str = "event.play_changed";
const EVENT_ASSET_CHANGED: &str = "event.asset_changed";

pub fn catalog() -> Vec<MethodSpec> {
    vec![
        // session / authority
        method(
            "session.hello",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, APP_CODE_PROTO],
            &[EVENT_SESSION_CHANGED],
        ),
        method(
            "session.ping",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION],
            &[],
        ),
        method(
            "session.goodbye",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION],
            &[EVENT_SESSION_CHANGED],
        ),
        method(
            "session.subscribe",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION],
            &[],
        ),
        method(
            "session.list",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION],
            &[],
        ),
        ui(
            "session.pause_actor",
            SideEffect::Mutating,
            Undo::None,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_UNAUTHORIZED],
            &[EVENT_SESSION_CHANGED],
        ),
        ui(
            "session.resume_actor",
            SideEffect::Mutating,
            Undo::None,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_UNAUTHORIZED],
            &[EVENT_SESSION_CHANGED],
        ),
        ui(
            "session.revoke",
            SideEffect::Mutating,
            Undo::None,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_UNAUTHORIZED],
            &[EVENT_SESSION_CHANGED],
        ),
        ui(
            "capability.grant",
            SideEffect::Mutating,
            Undo::None,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_UNAUTHORIZED],
            &[EVENT_SESSION_CHANGED],
        ),
        ui(
            "capability.revoke",
            SideEffect::Mutating,
            Undo::None,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_UNAUTHORIZED],
            &[EVENT_SESSION_CHANGED],
        ),
        method(
            "capability.list",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        ui(
            "confirmation.approve",
            SideEffect::Mutating,
            Undo::Special("executes the held command once; bind actor+hash+revision"),
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_UNAUTHORIZED, E_CONFLICT],
            &[EVENT_SCENE_CHANGED],
        ),
        ui(
            "confirmation.deny",
            SideEffect::Mutating,
            Undo::None,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_UNAUTHORIZED],
            &[],
        ),
        // project / scene
        method(
            "project.create",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_PROJECT_OPEN],
            &[EVENT_SESSION_CHANGED],
        ),
        method(
            "project.open",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_PROJECT_OPEN],
            &[EVENT_SESSION_CHANGED],
        ),
        method(
            "project.info",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION],
            &[],
        ),
        method(
            "project.save_all",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_PAUSED],
            &[],
        ),
        method(
            "project.settings_get",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION],
            &[],
        ),
        method(
            "project.settings_set",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "scene.new",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "scene.open",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "scene.save",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_PAUSED],
            &[],
        ),
        method(
            "scene.list",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION],
            &[],
        ),
        method(
            "scene.dump",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "scene.stats",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        // entity / component
        method(
            "entity.spawn",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_LOCKED, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "entity.destroy",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Destructive(
                "entity.destroy.mass — Destructive when mass (ids.length > 20; salami heuristic at >= 80% of that threshold)",
            ),
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_LOCKED, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED, EVENT_CONFIRMATION_REQUEST],
        ),
        method(
            "entity.duplicate",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_LOCKED, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "entity.reparent",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_LOCKED, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "entity.set_order",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_LOCKED, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "entity.rename",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_LOCKED, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "entity.find",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION],
            &[],
        ),
        method(
            "entity.lock",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_LOCKED, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "entity.unlock",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_LOCKED, E_PAUSED],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "component.set",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_LOCKED, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "component.add",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_LOCKED, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "component.remove",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_LOCKED, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "component.get",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "component.registry",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION],
            &[],
        ),
        method(
            "blueprint.create",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_LOCKED, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "blueprint.instantiate",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        // script (document/WAL + play hot-reload + editor buffers)
        method(
            "script.create",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "script.set_source",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "script.get_source",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "script.ingest_external",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "script.diagnostics",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "script.reload",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_PAUSED],
            &[],
        ),
        ui(
            "script.buffer_set",
            SideEffect::Mutating,
            Undo::None,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_UNAUTHORIZED],
            &[],
        ),
        method(
            "script.conflicts",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION],
            &[],
        ),
        ui(
            "script.conflict_resolve",
            SideEffect::Mutating,
            Undo::None,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_UNAUTHORIZED, E_PAUSED],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "inputmap.get",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION],
            &[],
        ),
        method(
            "inputmap.set",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "tilemap.set_cells",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_LOCKED, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "tilemap.fill_rect",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_LOCKED, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "build.game",
            SideEffect::Job,
            Undo::None,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_PATH, E_NOT_FOUND, E_PAUSED, E_BUDGET],
            &[],
        ),
        method(
            "build.status",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "build.cancel",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        // LIVE play / observe / judge / runtime / artifact / asset (MASTER 4.2)
        method(
            "play.start",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_PAUSED, E_BUDGET],
            &[EVENT_PLAY_CHANGED],
        ),
        method(
            "play.stop",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_PAUSED],
            &[EVENT_PLAY_CHANGED],
        ),
        method(
            "play.status",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION],
            &[],
        ),
        method(
            "play.pause",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_PAUSED],
            &[EVENT_PLAY_CHANGED],
        ),
        method(
            "play.resume",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_PAUSED],
            &[EVENT_PLAY_CHANGED],
        ),
        method(
            "play.step_frames",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_PAUSED],
            &[],
        ),
        method(
            "play.set_timescale",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_PAUSED],
            &[],
        ),
        method(
            "input.inject",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_PAUSED],
            &[],
        ),
        method(
            "obs.screenshot",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "obs.world_dump",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "obs.logs_tail",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "obs.perf",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "obs.events",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "obs.query",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "judge.run_until_event",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_PAUSED, E_BUDGET],
            &[],
        ),
        method(
            "judge.wait_event",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_PAUSED, E_BUDGET],
            &[],
        ),
        method(
            "judge.assert_world",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "judge.assert_perf",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "judge.assert_screenshot",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "judge.run_test",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_PAUSED, E_BUDGET],
            &[EVENT_PLAY_CHANGED],
        ),
        method(
            "runtime.copy_to_scene",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[
                E_VALIDATION,
                E_NOT_FOUND,
                E_LOCKED,
                E_CONFLICT,
                E_PAUSED,
                E_BUDGET,
            ],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "artifact.list",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND],
            &[],
        ),
        method(
            "artifact.get",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION, E_NOT_FOUND, E_PATH],
            &[],
        ),
        method(
            "artifact.gc",
            SideEffect::Mutating,
            Undo::None,
            Capability::Base,
            Idempotency::Natural,
            &[E_VALIDATION, E_NOT_FOUND, E_PAUSED],
            &[],
        ),
        method(
            "asset.import",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_PATH, E_NOT_FOUND, E_PAUSED, E_BUDGET],
            &[EVENT_ASSET_CHANGED],
        ),
        method(
            "asset.list",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION],
            &[],
        ),
        // transaction / undo
        method(
            "transaction.execute",
            SideEffect::Mutating,
            Undo::Auto,
            Capability::Base,
            Idempotency::ByCommandId,
            &[
                E_VALIDATION,
                E_NOT_FOUND,
                E_LOCKED,
                E_CONFLICT,
                E_PAUSED,
                E_BUDGET,
            ],
            &[EVENT_SCENE_CHANGED, EVENT_CONFIRMATION_REQUEST],
        ),
        ui(
            "undo.perform",
            SideEffect::Mutating,
            Undo::Special("UI undo stack; agent must use undo.revert_own"),
            Idempotency::Natural,
            &[E_VALIDATION, E_UNAUTHORIZED, E_CONFLICT, E_PAUSED],
            &[EVENT_SCENE_CHANGED],
        ),
        ui(
            "undo.redo",
            SideEffect::Mutating,
            Undo::Special("UI redo stack"),
            Idempotency::Natural,
            &[E_VALIDATION, E_UNAUTHORIZED, E_CONFLICT, E_PAUSED],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "undo.revert_own",
            SideEffect::Mutating,
            Undo::Special("inverse transaction of the caller's own txn when no later conflict"),
            Capability::Base,
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_CONFLICT, E_PAUSED, E_BUDGET],
            &[EVENT_SCENE_CHANGED],
        ),
        method(
            "undo.revert",
            SideEffect::Mutating,
            Undo::Special("inverse transaction of any actor; requires undo.others"),
            Capability::Destructive("undo.others"),
            Idempotency::ByCommandId,
            &[E_VALIDATION, E_NOT_FOUND, E_CONFLICT, E_PAUSED, E_BUDGET, E_UNAUTHORIZED],
            &[EVENT_SCENE_CHANGED, EVENT_CONFIRMATION_REQUEST],
        ),
        method(
            "undo.history",
            SideEffect::ReadOnly,
            Undo::None,
            Capability::Base,
            Idempotency::NotApplicable,
            &[E_VALIDATION],
            &[],
        ),
    ]
}

fn method(
    name: &'static str,
    side_effect: SideEffect,
    undo: Undo,
    capability: Capability,
    idempotency: Idempotency,
    errors: &[&'static str],
    emits: &[&'static str],
) -> MethodSpec {
    MethodSpec {
        name,
        side_effect,
        undo,
        capability,
        idempotency,
        errors: errors.to_vec(),
        emits: emits.to_vec(),
    }
}

fn ui(
    name: &'static str,
    side_effect: SideEffect,
    undo: Undo,
    idempotency: Idempotency,
    errors: &[&'static str],
    emits: &[&'static str],
) -> MethodSpec {
    method(
        name,
        side_effect,
        undo,
        Capability::UiOnly,
        idempotency,
        errors,
        emits,
    )
}
