//! PROTOCOL.md codegen from the executable registry.

use crate::{all_methods, MethodSpec};
use gs_protocol::{
    APP, APP_CODE_PROTO, BUSY, CONFLICT, IDLE_TIMEOUT_SECS, INVALID_PARAMS, INVALID_REQUEST,
    MAX_LINE_BYTES, METHOD_NOT_FOUND, PARSE, PROTOCOL_VER, SLOWLORIS_SECS, UNAUTHORIZED,
};
use std::fmt::Write as _;
use std::path::Path;

/// Render `docs/PROTOCOL.md` from [`crate::all_methods`].
pub fn generate_protocol_md() -> String {
    let methods = all_methods();
    let mut out = String::new();

    out.push_str("# HH Game Studio Protocol\n\n");
    out.push_str("> AUTO-GENERATED by `gs-registry`. Do not edit by hand.\n");
    out.push_str("> Source of truth: `crates/gs-registry` (MASTER 4.0).\n\n");

    out.push_str("## Envelope and framing\n\n");
    let _ = writeln!(out, "- `protocol_ver`: `{PROTOCOL_VER}`");
    out.push_str("- Transport: TCP `127.0.0.1`\n");
    out.push_str("- Framing: NDJSON — one UTF-8 JSON-RPC 2.0 message per line, terminated by LF\n");
    let _ = writeln!(
        out,
        "- Max line: {MAX_LINE_BYTES} bytes (4 MiB). Over cap → `{INVALID_REQUEST}` / `{APP_CODE_PROTO}`, then close that connection (GS-EC-58)."
    );
    let _ = writeln!(
        out,
        "- Slowloris: a line that is not finished in {SLOWLORIS_SECS}s closes the connection."
    );
    let _ = writeln!(
        out,
        "- Idle timeout: {IDLE_TIMEOUT_SECS}s (keep alive with `session.ping`)."
    );
    let _ = writeln!(
        out,
        "- JSON-RPC array batch: **not supported** (server returns `{INVALID_REQUEST}`). Use `transaction.execute`."
    );
    out.push_str("- Events are JSON-RPC notifications (no `id`).\n");
    out.push_str("- `error.code` is numeric; application codes live in `error.data.app_code`.\n");
    out.push_str("- After handshake, identity comes from the connection. Clients do not self-declare `actor_id`.\n");
    let _ = writeln!(
        out,
        "- Methods marked **[UI]** have `capability: UiOnly` and must be rejected for principal `agent` (`{UNAUTHORIZED}`).\n"
    );

    out.push_str("### JSON-RPC `error.code`\n\n");
    out.push_str("| code | meaning |\n");
    out.push_str("| --- | --- |\n");
    let _ = writeln!(out, "| `{PARSE}` | parse error |");
    let _ = writeln!(
        out,
        "| `{INVALID_REQUEST}` | invalid request / batch / proto |"
    );
    let _ = writeln!(out, "| `{METHOD_NOT_FOUND}` | method not found |");
    let _ = writeln!(out, "| `{INVALID_PARAMS}` | invalid params |");
    let _ = writeln!(
        out,
        "| `{APP}` | application error (`error.data.app_code`) |"
    );
    let _ = writeln!(out, "| `{UNAUTHORIZED}` | unauthorized / wrong principal |");
    let _ = writeln!(out, "| `{CONFLICT}` | conflict |");
    let _ = writeln!(out, "| `{BUSY}` | busy / budget |\n");

    let _ = writeln!(out, "## Methods ({})\n", methods.len());
    out.push_str("| name | side_effect | undo | capability | idempotency | UI |\n");
    out.push_str("| --- | --- | --- | --- | --- | --- |\n");
    for spec in methods {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} | {} | {} |",
            spec.name,
            spec.side_effect,
            markdown_cell(&spec.undo.to_string()),
            markdown_cell(&spec.capability.to_string()),
            spec.idempotency,
            ui_mark(spec),
        );
    }
    out.push('\n');

    out.push_str("## Method details\n\n");
    for spec in methods {
        let _ = writeln!(out, "### `{}`{}\n", spec.name, ui_heading(spec));
        let _ = writeln!(out, "- **side_effect:** {}", spec.side_effect);
        let _ = writeln!(out, "- **undo:** {}", spec.undo);
        let _ = writeln!(out, "- **capability:** {}", spec.capability);
        let _ = writeln!(out, "- **idempotency:** {}", spec.idempotency);
        let _ = writeln!(out, "- **errors:** {}", join_codes(&spec.errors));
        let _ = writeln!(out, "- **emits:** {}", join_codes(&spec.emits));
        out.push('\n');
    }

    out
}

/// Write generated PROTOCOL.md to `path` (typically repo `docs/PROTOCOL.md`).
pub fn write_protocol_md(path: impl AsRef<Path>) -> std::io::Result<()> {
    let path = path.as_ref();
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)?;
        }
    }
    std::fs::write(path, generate_protocol_md())
}

fn ui_mark(spec: &MethodSpec) -> &'static str {
    if spec.is_ui_only() {
        "[UI]"
    } else {
        ""
    }
}

fn ui_heading(spec: &MethodSpec) -> &'static str {
    if spec.is_ui_only() {
        " [UI]"
    } else {
        ""
    }
}

fn join_codes(codes: &[&str]) -> String {
    if codes.is_empty() {
        return "_(none)_".to_string();
    }
    codes
        .iter()
        .map(|c| format!("`{c}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn markdown_cell(value: &str) -> String {
    value.replace('|', "\\|")
}
