#!/usr/bin/env python3
"""Deterministic Scrap Yard pixel-art generator.

Each sprite is an ASCII map (one character per pixel) plus a palette dict.
'.' is always transparent. Edit a map, re-run this file, PNGs overwrite.

    python tools/art-gen/gen_scrap_yard_art.py
"""

from __future__ import annotations

import json
import struct
import sys
import zlib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ASSETS_DIR = REPO_ROOT / "games" / "scrap-yard" / "assets"
INDEX_PATH = ASSETS_DIR / "index.json"
CONTACT_PATH = Path(__file__).resolve().parent / "contact_sheet.png"

PNG_MAGIC = b"\x89PNG\r\n\x1a\n"

# ---------------------------------------------------------------------------
# Palettes — ~6 colours per character; industrial dark for the yard.
# ---------------------------------------------------------------------------

VELA = {
    "#": (10, 14, 20, 255),  # outline / boots / mouth
    "h": (24, 44, 52, 255),  # short dark-teal hair
    "s": (236, 188, 156, 255),  # skin
    "c": (28, 164, 160, 255),  # cyan jacket
    "k": (16, 70, 76, 255),  # jacket/pants shade
    "l": (118, 236, 220, 255),  # rim + goggle glass
    "w": (252, 252, 255, 255),  # eyes / fist highlight
}

ROOK = {
    "#": (16, 10, 8, 255),  # outline / boots / mouth
    "m": (52, 44, 40, 255),  # welding mask (flipped up)
    "s": (214, 164, 126, 255),  # skin / squared jaw
    "r": (196, 86, 38, 255),  # rust body
    "k": (116, 42, 20, 255),  # rust shade / pants
    "l": (236, 158, 86, 255),  # rim
    "w": (252, 252, 255, 255),  # eyes
}

STEEL = {
    "s": (40, 44, 50, 255),
    "m": (58, 64, 72, 255),
    "n": (28, 30, 34, 255),
    "r": (108, 116, 126, 255),
    "h": (168, 176, 186, 255),
}

HULL = {
    "d": (16, 22, 36, 255),
    "b": (30, 42, 64, 255),
    "g": (48, 62, 86, 255),
    "#": (78, 90, 112, 255),
    "r": (96, 108, 128, 255),
}

CATWALK = {
    "h": (210, 214, 220, 255),
    "m": (132, 136, 144, 255),
    "p": (176, 180, 186, 255),
    "#": (72, 76, 84, 255),
}

PANEL = {
    "d": (12, 16, 28, 255),
    "b": (22, 32, 52, 255),
    "v": (8, 12, 22, 255),
    "g": (40, 56, 80, 255),
    "p": (34, 48, 74, 255),
    "h": (72, 94, 124, 255),
    "o": (168, 132, 48, 255),
}

LAMP = {
    "#": (18, 16, 14, 255),
    "c": (92, 96, 104, 255),
    "y": (255, 196, 64, 255),
    "w": (255, 244, 200, 255),
    "g": (255, 170, 40, 140),
    "e": (255, 120, 20, 70),
}

WOOD = {
    "#": (28, 18, 10, 255),
    "w": (168, 112, 58, 255),
    "d": (118, 74, 36, 255),
    "k": (72, 44, 20, 255),
}

HAZARD = {
    "#": (20, 10, 8, 255),
    "r": (184, 36, 32, 255),
    "y": (220, 176, 36, 255),
    "w": (232, 96, 72, 255),
    "k": (96, 18, 16, 255),
}

LADDER = {
    "#": (120, 126, 134, 255),
    "s": (72, 78, 86, 255),
}

PIPE = {
    "#": (16, 18, 22, 255),
    "s": (96, 104, 112, 255),
    "l": (168, 176, 184, 255),
    "k": (56, 60, 66, 255),
}

BLASTER = {
    "#": (14, 16, 20, 255),
    "s": (64, 72, 80, 255),
    "k": (36, 42, 48, 255),
    "l": (80, 170, 168, 255),
    "w": (200, 255, 240, 255),
}

BOMB = {
    "#": (16, 12, 10, 255),
    "k": (48, 44, 40, 255),
    "r": (156, 52, 36, 255),
    "w": (200, 96, 64, 255),
    "y": (255, 188, 48, 255),
}

CLOCK = {
    "#": (28, 18, 8, 255),
    "o": (196, 148, 56, 255),
    "l": (232, 196, 96, 255),
    "d": (120, 84, 28, 255),
    "w": (248, 236, 200, 255),
}

BOLT = {
    "#": (12, 28, 32, 255),
    "l": (64, 220, 200, 255),
    "w": (230, 255, 250, 255),
}

HP_BACK = {
    "#": (20, 16, 16, 255),
    "d": (56, 24, 24, 255),
}

HP_FILL = {
    "w": (255, 255, 255, 255),
}

# ---------------------------------------------------------------------------
# ASCII maps — contract dest names, exact pixel sizes.
# ---------------------------------------------------------------------------

SPRITES: list[dict] = []


def _add(
    asset_id: str,
    dest_name: str,
    w: int,
    h: int,
    palette: dict,
    ascii_map: str,
) -> None:
    SPRITES.append(
        {
            "asset_id": asset_id,
            "dest_rel": f"assets/{dest_name}",
            "dest_name": dest_name,
            "w": w,
            "h": h,
            "palette": palette,
            "ascii_map": ascii_map,
        }
    )


# --- tiles -----------------------------------------------------------------

_add(
    "a_000001",
    "tile_floor.png",
    16,
    16,
    STEEL,
    """
ssssssssssssssss
smmmmmmmmmmmmmms
smrhmmmmmmmmrhms
smhhmmmmmmmmhhms
smmmmmmmmmmmmmms
smmmmmnnnnmmmmms
smmmmmnnnnmmmmms
smmmmmmmmmmmmmms
smmmmmmmmmmmmmms
smmmmmnnnnmmmmms
smmmmmnnnnmmmmms
smmmmmmmmmmmmmms
smrhmmmmmmmmrhms
smhhmmmmmmmmhhms
smmmmmmmmmmmmmms
ssssssssssssssss
""",
)

_add(
    "a_000002",
    "tile_wall.png",
    16,
    16,
    HULL,
    """
dddddddddddddddd
dbbbbbggbbbbbbbd
dbbbbb##bbbbbbbd
dbrrbbggbbrrbbbd
dbbbbbggbbbbbbbd
dbbbbb##bbbbbbbd
dbbbbbggbbbbbbbd
dbrrbbggbbrrbbbd
dbrrbbggbbrrbbbd
dbbbbbggbbbbbbbd
dbbbbb##bbbbbbbd
dbbbbbggbbbbbbbd
dbrrbbggbbrrbbbd
dbbbbb##bbbbbbbd
dbbbbbggbbbbbbbd
dddddddddddddddd
""",
)

_add(
    "a_000003",
    "tile_plat.png",
    16,
    16,
    CATWALK,
    """
hhhhhhhhhhhhhhhh
mmmmmmmmmmmmmmmm
m#pp#pp#pp#pp#pm
mp#pp#pp#pp#pp#m
m#pp#pp#pp#pp#pm
mp#pp#pp#pp#pp#m
m#pp#pp#pp#pp#pm
mp#pp#pp#pp#pp#m
m#pp#pp#pp#pp#pm
mp#pp#pp#pp#pp#m
m#pp#pp#pp#pp#pm
mp#pp#pp#pp#pp#m
m#pp#pp#pp#pp#pm
mp#pp#pp#pp#pp#m
mmmmmmmmmmmmmmmm
hhhhhhhhhhhhhhhh
""",
)

_add(
    "a_000010",
    "bg_panel.png",
    32,
    32,
    PANEL,
    """
ddddddddddddddddddddppppdddddddd
ddddddddddddddddddddphhpdddddddd
ddobbobdddddddddddddphhpdddddddd
dbvvvvvbddddddddddddphhpdddddddd
dbvgvgvgbdddddddddddphhpdddddddd
dbvvvvvbddddddddddddphhpdddddddd
dbvgvgvgbdddddddddddphhpdddddddd
dbvvvvvbddddddddddddphhpdddddddd
ddobbobdddddddddddddppppdddddddd
ddddddddddddddddddddppppdddddddd
ddddddddddddddddddddppppdddddddd
ddddddddddddddddddddppppdddddddd
pppppppppppppppppppppppppppppppp
phhhhhhhhhhhhhhhhhhhhhhhhhhhhhhp
pppppppppppppppppppppppppppppppp
ddddddddddddddddddddppppdddddddd
ddddddddddddddddddddppppdddddddd
ddddbbbbbbbbbbddddddppppdddddddd
ddddbvvvvvvvvbddddddphhpdddddddd
ddddbvgvgvgvgbddddddphhpdddddddd
ddddbvvvvvvvvbddddddphhpdddddddd
ddddbbbbbbbbbbddddddppppdddddddd
ddddddddddddddddddddppppdddddddd
ddddddddddddddddddddppppdddddddd
ddobbobdddddddddddddppppdddddddd
ddddddddddddddddddddppppdddddddd
ddddddddddddddddddddppppdddddddd
ddddddddddddddddddddppppdddddddd
ddddddddddddddddddddppppdddddddd
ddddddddddddddddddddphhpdddddddd
ddddddddddddddddddddphhpdddddddd
ddddddddddddddddddddppppdddddddd
""",
)

# --- props -----------------------------------------------------------------

_add(
    "a_000011",
    "lamp.png",
    16,
    16,
    LAMP,
    """
.......##.......
......#cc#......
.......##.......
.....###c###....
....#c#ccc#c#...
...#c#cyyyc#c#..
...#c#cywyc#c#..
...#c#cyyyc#c#..
....#c#ccc#c#...
.....###c###....
.....#egggge#...
....#e.....e#...
....#e.....e#...
.....#e...e#....
......#eee#.....
................
""",
)

_add(
    "a_000012",
    "crate.png",
    16,
    16,
    WOOD,
    """
................
.##############.
.#wwwwwwwwwwww#.
.#w##########w#.
.#w#dddddddd#w#.
.#w#d#dddd#d#w#.
.#w#dd#dd#dd#w#.
.#w#ddd##ddd#w#.
.#w#dd#dd#dd#w#.
.#w#d#dddd#d#w#.
.#w#dddddddd#w#.
.#w##########w#.
.#wwwwwwwwwwww#.
.##############.
.#kkkkkkkkkkkk#.
................
""",
)

_add(
    "a_000013",
    "barrel.png",
    16,
    16,
    HAZARD,
    """
................
.....######.....
....#rrrrrr#....
...#rrwwrrrr#...
...#rrrrrrrr#...
...#rryyyyrr#...
...#rryyyyrr#...
...#rrrrrrrr#...
...#rrwwrrrr#...
...#rrrrrrrr#...
...#rrrrrrrr#...
...#kkkkkkkk#...
...#rrrrrrrr#...
....#rrrrrr#....
.....######.....
................
""",
)

_add(
    "a_000014",
    "ladder.png",
    16,
    16,
    LADDER,
    """
#s............s#
#s............s#
#s..########..s#
#s............s#
#s............s#
#s..########..s#
#s............s#
#s............s#
#s..########..s#
#s............s#
#s............s#
#s..########..s#
#s............s#
#s............s#
#s............s#
#s............s#
""",
)

# --- Vela (lean cyan courier, goggles up, ~12 px body, faces right) --------

_add(
    "a_000020",
    "vela_idle.png",
    24,
    32,
    VELA,
    """
........................
........#####...........
......#########.........
.....##lll#.#lll#.......
.....#llll#.#llll#......
.....##lll#.#lll##......
.....#hhsssssss#........
.....#hswsswsss#........
.....#hssssssss#........
......#sss#sss##........
.......#sssss#..........
.......##ccc##..........
......#lccccck#.........
.....#lccccccck#........
.....#cccccccck#........
.....#ccc##ccck#........
....#lcc#..#cck#........
....#ccc#..#cck#........
.....#kk#..#kkk#........
.....#kk#..#kkk#........
.....#kk#..#kkk#........
.....#kk#..#kkk#........
.....#kk#..#kkk#........
.....#kk#..#kkk#........
.....#kk#..#kkk#........
.....##k#..#kk##........
.....#kk#..#kkk#........
.....#kk#..#kkk#........
....######.######.......
....#kkkk#.#kkkk#.......
....#kkkk#.#kkkk#.......
....######.######.......
""",
)

_add(
    "a_000021",
    "vela_walk_a.png",
    24,
    32,
    VELA,
    """
........................
.........#####..........
.......#########........
......##lll#.#lll#......
......#llll#.#llll#.....
......##lll#.#lll##.....
......#hhsssssss#.......
......#hswsswsss#.......
......#hssssssss#.......
.......#sss#sss##.......
........#sssss#.........
........##ccc##.........
.......#lccccck#........
..#####lccccccck#.......
.##lll#cccccccck#.......
.#lwww#ccc##ccck#.......
.##lll#cc#..#cck##......
....#kkk#..#kk#..##.....
....#kkk#..#kk#.#kk#....
....#kk#...#kkk##kk#....
....#kk#....#kk#.#k#....
...##k#.....#kk##k#.....
...#kk#.....#kkk#.......
...#kk#.....##kk#.......
...#kk#......#kk#.......
...#kk#......#kk##......
..##kk#......#kkk#......
..#kkk#......#kkk#......
.######......#####......
.#kkkk#......#kkk#......
.#kkkk#......#kkk#......
.######......#####......
""",
)

_add(
    "a_000022",
    "vela_walk_b.png",
    24,
    32,
    VELA,
    """
........................
........#####...........
......#########.........
.....##lll#.#lll#.......
.....#llll#.#llll#......
.....##lll#.#lll##......
.....#hhsssssss#........
.....#hswsswsss#........
.....#hssssssss#........
......#sss#sss##........
.......#sssss#..........
.......##ccc##..........
......#lccccck######....
.....#lcccccccklll##....
.....#cccccccckwww#.....
.....#ccc##cccklll#.....
....##cc#..#cck##.......
...#kk#....#kkk#........
...#kk#....#kkk#........
..##kk#...#kk#..........
..#kkk#...#kk#..........
..#kkk#..##k#...........
...#kk#..#kk#...........
...#kk#..#kk#...........
...#kk#..#kk#...........
...#kk##.#kk#...........
...#kkk#.#kk##..........
...#kkk#.#kkk#..........
...#####.######.........
...#kkk#.#kkkk#.........
...#kkk#.#kkkk#.........
...#####.######.........
""",
)

_add(
    "a_000023",
    "vela_punch.png",
    24,
    32,
    VELA,
    """
........................
.........#####..........
.......#########........
......##lll#.#lll#......
......#llll#.#llll#.....
......##lll#.#lll##.....
......#hhsssssss#.......
......#hswsswsss#.......
......#hssssssss#.......
.......#sss#sss##.......
........#sssss#.........
........##ccc##.........
.......#lccccck#########
......#lcccccccccccclll#
......#cccccccccccclwww#
......#ccc##ccccccclll##
.....#lcc#..#cck########
.....#ccc#..#cck#.......
......#kk#..#kkk#.......
......#kk#..#kkk#.......
......#kk#..#kkk#.......
......#kk#..#kkk#.......
......#kk#..#kkk#.......
......#kk#..#kkk#.......
......#kk#..#kkk#.......
......##k#..#kk##.......
......#kk#..#kkk#.......
......#kk#..#kkk#.......
.....######.######......
.....#kkkk#.#kkkk#......
.....#kkkk#.#kkkk#......
.....######.######......
""",
)

_add(
    "a_000024",
    "vela_crouch.png",
    24,
    32,
    VELA,
    """
........................
........................
........................
........................
........................
........................
........................
........................
........#####...........
......#########.........
.....##lll#.#lll#.......
.....#llll#.#llll#......
.....##lll#.#lll##......
.....#hhsssssss#........
.....#hswsswsss#........
.....#hssssssss#........
......#sss#sss##........
.......#sssss#..........
......##ccccc##.........
....###lccccck###.......
...#llllllllcckk#.......
...#lwwww#cccckk#.......
....####kkkkkkk#........
....#kkkkkkkkkk#........
...##kk#....#kk##.......
...#kk#......#kk#.......
...#kk#......#kk#.......
..##kk#......#kk##......
..#kkk#......#kkk#......
..#kkk#......#kkk#......
..#kkk#......#kkk#......
..#####......#####......
""",
)

_add(
    "a_000025",
    "vela_hurt.png",
    24,
    32,
    VELA,
    """
....#####...............
..#########.............
.##lll#.#lll#...........
.#llll#.#llll#..........
.##lll#.#lll##..........
.#hhsssssss#............
.#hswsswsss#............
.#hss##sss#.............
..#ssssss#..............
...#ss#.................
....##ccc##.............
...#lccccck#............
..#lccccccck#...........
..#cccccccck#...........
..#ccc##ccck#...........
.#lcc#..#cck#...........
.#ccc#..#cck#...........
..#kk#..#kkk#...........
..#kk#..#kkk#...........
..#kk#..#kkk#...........
..#kk#..#kkk#...........
..#kk#..#kkk#...........
..#kk#..#kkk#...........
..##k#..#kk##...........
..#kk#..#kkk#...........
..#kk#..#kkk#...........
.######..#####..........
.#kkkk#..#kkk#..........
.#kkkk#..#kkk#..........
.#kkkk#..#kkk#..........
.######..#####..........
.######..#####..........
""",
)

# --- Rook (heavy rust breaker, mask up, ~18 px body, faces right) ----------

_add(
    "a_000030",
    "rook_idle.png",
    24,
    32,
    ROOK,
    """
........................
......############......
.....#mmmmmmmmmmmm#.....
.....#mm##mmmm##mm#.....
.....#mmmmmmmmmmmm#.....
....###sssssssssss##....
....#ssssssssssssss#....
....#sswssswsssssss#....
....#ssssssssssssss#....
....#sssss###ssssss#....
....#ssssssssssssss#....
.....#ssssssssssss#.....
...##lrrrrrrrrrrrrk##...
..#lrrrrrrrrrrrrrrrk#...
..#rrrrrrrrrrrrrrrrk#...
..#rrrrrrrrrrrrrrrrk#...
..#rrr##rrrrrr##rrrk#...
.#lrr#..#rrrr#..#rrk#...
.#rrr#..#rrrr#..#rrk#...
..#kkkkk#..#kkkkk#......
..#kkkkk#..#kkkkk#......
...#kkkk#..#kkkk#.......
...#kkkk#..#kkkk#.......
...#kkkk#..#kkkk#.......
...#kkkk#..#kkkk#.......
...#kkkk#..#kkkk#.......
...##kkk#..#kkk##.......
...#kkkk#..#kkkk#.......
..########.########.....
..#kkkkkk#.#kkkkkk#.....
..#kkkkkk#.#kkkkkk#.....
..########.########.....
""",
)

_add(
    "a_000031",
    "rook_walk_a.png",
    24,
    32,
    ROOK,
    """
........................
.......############.....
......#mmmmmmmmmmmm#....
......#mm##mmmm##mm#....
......#mmmmmmmmmmmm#....
.....###sssssssssss##...
.....#ssssssssssssss#...
.....#sswssswsssssss#...
.....#ssssssssssssss#...
.....#sssss###ssssss#...
.....#ssssssssssssss#...
......#ssssssssssss#....
....##lrrrrrrrrrrrrk##..
.#####rrrrrrrrrrrrrrk#..
#llll#rrrrrrrrrrrrrrk#..
#lwww#rrr##rrrr##rrrk#..
#llll#rr#..#rr#..#rrk#..
.####kkk#..#rr#..#rrk#..
....#kkk#..#kkk#..##....
....#kk#...#kkk#.#kk#...
....#kk#....#kk##kkk#...
...##k#.....#kk#.#kk#...
...#kk#.....#kkk#.......
...#kk#.....##kk#.......
...#kk#......#kk#.......
...#kk#......#kk##......
..##kk#......#kkk#......
..#kkk#......#kkk#......
.########....######.....
.#kkkkkk#....#kkkk#.....
.#kkkkkk#....#kkkk#.....
.########....######.....
""",
)

_add(
    "a_000032",
    "rook_walk_b.png",
    24,
    32,
    ROOK,
    """
........................
......############......
.....#mmmmmmmmmmmm#.....
.....#mm##mmmm##mm#.....
.....#mmmmmmmmmmmm#.....
....###sssssssssss##....
....#ssssssssssssss#....
....#sswssswsssssss#....
....#ssssssssssssss#....
....#sssss###ssssss#....
....#ssssssssssssss#....
.....#ssssssssssss#.....
...##lrrrrrrrrrrrrk#####
..#lrrrrrrrrrrrrrrkllll#
..#rrrrrrrrrrrrrrrkwwwl#
..#rrrrrrrrrrrrrrrkllll#
..#rrr##rrrrrr##rrk#####
.#lrr#..#rrrr#..#kk#....
.#rrr#..#rrrr#..#kk#....
..#kk#...#kk#..#kk#.....
..#kk#...#kk#..#kk#.....
...#kk#..#kk#.##k#......
...#kk#..#kk#.#kk#......
...#kk#..#kk#.#kk#......
...#kk#..#kk#.#kk#......
...#kk##.#kk#.#kk#......
...#kkk#.#kk##kk#.......
...#kkk#.#kkk#kk#.......
...######.#########.....
...#kkkk#.#kkkkkkk#.....
...#kkkk#.#kkkkkkk#.....
...######.#########.....
""",
)

_add(
    "a_000033",
    "rook_punch.png",
    24,
    32,
    ROOK,
    """
........................
.......############.....
......#mmmmmmmmmmmm#....
......#mm##mmmm##mm#....
......#mmmmmmmmmmmm#....
.....###sssssssssss##...
.....#ssssssssssssss#...
.....#sswssswsssssss#...
.....#ssssssssssssss#...
.....#sssss###ssssss#...
.....#ssssssssssssss#...
......#ssssssssssss#....
....##lrrrrrrrrrr#######
...#lrrrrrrrrrrrrllllll#
...#rrrrrrrrrrrrrwwwwwl#
...#rrrrrrrrrrrrrllllll#
...#rrr##rrrrrr#########
..#lrr#..#rrrk#.........
..#rrr#..#rrrk#.........
...#kkkkk#.#kkk#........
...#kkkkk#.#kkk#........
....#kkkk#.#kk#.........
....#kkkk#.#kk#.........
....#kkkk#.#kk#.........
....#kkkk#.#kk#.........
....#kkkk#.#kk#.........
....##kkk#.#k##.........
....#kkkk#.#kk#.........
...########.######......
...#kkkkkk#.#kkkk#......
...#kkkkkk#.#kkkk#......
...########.######......
""",
)

_add(
    "a_000034",
    "rook_crouch.png",
    24,
    32,
    ROOK,
    """
........................
........................
........................
........................
........................
........................
........................
........................
......############......
.....#mmmmmmmmmmmm#.....
.....#mm##mmmm##mm#.....
.....#mmmmmmmmmmmm#.....
....###sssssssssss##....
....#ssssssssssssss#....
....#sswssswsssssss#....
....#ssssssssssssss#....
....#sssss###ssssss#....
....#ssssssssssssss#....
.....#ssssssssssss#.....
..###lrrrrrrrrrrrk###...
.#llllrrrrrrrrrrrrkk#...
.#wwwwrrr##rrrr#kkk#....
..####kkkkkkkkkkkk#.....
...#kkkkkkkkkkkkkk#.....
..##kkk#......#kkk##....
..#kkk#........#kkk#....
..#kkk#........#kkk#....
.##kkk#........#kkk##...
.#kkkk#........#kkkk#...
.#kkkk#........#kkkk#...
.#kkkk#........#kkkk#...
.######........######...
""",
)

_add(
    "a_000035",
    "rook_hurt.png",
    24,
    32,
    ROOK,
    """
....############........
...#mmmmmmmmmmmm#.......
...#mm##mmmm##mm#.......
...#mmmmmmmmmmmm#.......
..###sssssssssss##......
..#ssssssssssssss#......
..#sswssswsssssss#......
..#ssssssssssssss#......
..#sss##ssssssss#.......
..#sssssssssssss#.......
...#ssssssssss#.........
....##rrrrrrr##.........
...##lrrrrrrrrrk##......
..#lrrrrrrrrrrrrrk#.....
..#rrrrrrrrrrrrrrk#.....
..#rrrrrrrrrrrrrrk#.....
..#rrr##rrrr##rrrk#.....
.#lrr#..#rr#..#rrk#.....
.#rrr#..#rr#..#rrk#.....
..#kkkkk#.#kkkkk#.......
..#kkkkk#.#kkkkk#.......
...#kkkk#.#kkkk#........
...#kkkk#.#kkkk#........
...#kkkk#.#kkkk#........
...#kkkk#.#kkkk#........
...##kkk#.#kkk##........
...#kkkk#.#kkkk#........
..########.#######......
..#kkkkkk#.#kkkkk#......
..#kkkkkk#.#kkkkk#......
..#kkkkkk#.#kkkkk#......
..########.#######......
""",
)

# --- weapons / pickups / UI ------------------------------------------------

_add(
    "a_000040",
    "pipe.png",
    16,
    16,
    PIPE,
    """
................
................
................
................
.##############.
#ssllllllllllss#
#ssssssssssssss#
.##############.
...###..........
...#k#..........
...###..........
................
................
................
................
................
""",
)

_add(
    "a_000041",
    "blaster.png",
    16,
    16,
    BLASTER,
    """
................
................
.........##.....
..#####.#ll#....
.#skkkk#llll#...
.#skkkk#lwwl##..
.#skkkk#llll#...
..##.####ll#....
..#s#....##.....
..#s#...........
..#s#...........
..###...........
................
................
................
................
""",
)

_add(
    "a_000042",
    "bomb.png",
    16,
    16,
    BOMB,
    """
................
...........ww...
..........#y#...
.........#y#....
.....########...
....#kkkkkkkk#..
...#krrrrrrrrk#.
...#krrwwrrrrk#.
...#krrrrrrrrk#.
...#krrrrrrrrk#.
....#kkkkkkkk#..
.....########...
................
................
................
................
""",
)

_add(
    "a_000043",
    "clock.png",
    16,
    16,
    CLOCK,
    """
.......##.......
......#dd#......
.....#d##d#.....
....#ooooooo#...
...#olw#.#wlo#..
...#ow#ooo#wo#..
...#ooo#ooooo#..
...#oooo#oooo#..
...#oo###oooo#..
...#olw#.#wlo#..
....#ooooooo#...
.....#ddddd#....
......#####.....
................
................
................
""",
)

_add(
    "a_000044",
    "bolt.png",
    8,
    8,
    BOLT,
    """
.#llll#.
#lwwwwl#
#lwwwll#
.#ll##l#
....#l#.
....#l#.
.....##.
........
""",
)

_add(
    "a_000050",
    "hp_back.png",
    16,
    4,
    HP_BACK,
    """
################
#dddddddddddddd#
#dddddddddddddd#
################
""",
)

_add(
    "a_000051",
    "hp_fill.png",
    16,
    4,
    HP_FILL,
    """
wwwwwwwwwwwwwwww
wwwwwwwwwwwwwwww
wwwwwwwwwwwwwwww
wwwwwwwwwwwwwwww
""",
)


# ---------------------------------------------------------------------------
# PNG I/O (stdlib only)
# ---------------------------------------------------------------------------


def _chunk(tag: bytes, data: bytes) -> bytes:
    crc = zlib.crc32(tag + data) & 0xFFFFFFFF
    return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", crc)


def write_png(path: Path, w: int, h: int, rgba: bytes) -> None:
    if len(rgba) != w * h * 4:
        raise ValueError(f"{path}: pixel buffer {len(rgba)} != {w}*{h}*4")
    raw = bytearray()
    stride = w * 4
    for y in range(h):
        raw.append(0)
        raw.extend(rgba[y * stride : (y + 1) * stride])
    ihdr = struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0)
    blob = PNG_MAGIC + _chunk(b"IHDR", ihdr)
    blob += _chunk(b"IDAT", zlib.compress(bytes(raw), 9))
    blob += _chunk(b"IEND", b"")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(blob)


def _paeth(a: int, b: int, c: int) -> int:
    p = a + b - c
    pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
    if pa <= pb and pa <= pc:
        return a
    if pb <= pc:
        return b
    return c


def read_png(path: Path) -> tuple[int, int, bytes]:
    data = path.read_bytes()
    if data[:8] != PNG_MAGIC:
        raise ValueError(f"{path} is not a PNG")
    pos = 8
    width = height = None
    idat = bytearray()
    while pos + 8 <= len(data):
        (length,) = struct.unpack(">I", data[pos : pos + 4])
        tag = data[pos + 4 : pos + 8]
        chunk = data[pos + 8 : pos + 8 + length]
        pos += 12 + length
        if tag == b"IHDR":
            width, height, bit, color, comp, filt, inter = struct.unpack(
                ">IIBBBBB", chunk
            )
            if (bit, color, comp, filt, inter) != (8, 6, 0, 0, 0):
                raise ValueError(f"{path}: unsupported IHDR")
        elif tag == b"IDAT":
            idat.extend(chunk)
        elif tag == b"IEND":
            break
    if width is None or height is None:
        raise ValueError(f"{path}: missing IHDR")
    raw = zlib.decompress(bytes(idat))
    stride = width * 4
    expected = height * (1 + stride)
    if len(raw) != expected:
        raise ValueError(f"{path}: bad IDAT size {len(raw)} != {expected}")
    out = bytearray(height * stride)
    prev = bytes(stride)
    for y in range(height):
        ftype = raw[y * (1 + stride)]
        row = bytearray(raw[y * (1 + stride) + 1 : (y + 1) * (1 + stride)])
        if ftype == 0:
            pass
        elif ftype == 1:
            for i in range(stride):
                left = row[i - 4] if i >= 4 else 0
                row[i] = (row[i] + left) & 255
        elif ftype == 2:
            for i in range(stride):
                row[i] = (row[i] + prev[i]) & 255
        elif ftype == 3:
            for i in range(stride):
                left = row[i - 4] if i >= 4 else 0
                row[i] = (row[i] + ((left + prev[i]) // 2)) & 255
        elif ftype == 4:
            for i in range(stride):
                left = row[i - 4] if i >= 4 else 0
                upleft = prev[i - 4] if i >= 4 else 0
                row[i] = (row[i] + _paeth(left, prev[i], upleft)) & 255
        else:
            raise ValueError(f"{path}: filter {ftype}")
        out[y * stride : (y + 1) * stride] = row
        prev = bytes(row)
    return width, height, bytes(out)


# ---------------------------------------------------------------------------
# Rasterise ASCII maps
# ---------------------------------------------------------------------------


def parse_map(text: str, w: int, h: int, name: str) -> list[str]:
    lines = text.strip("\n").split("\n")
    if len(lines) != h:
        raise ValueError(f"{name}: expected {h} rows, got {len(lines)}")
    for i, line in enumerate(lines):
        if len(line) != w:
            raise ValueError(
                f"{name}: row {i} has {len(line)} cols, expected {w}: {line!r}"
            )
    return lines


def rasterise(sprite: dict) -> bytes:
    name = sprite["dest_name"]
    w, h = sprite["w"], sprite["h"]
    palette = sprite["palette"]
    rows = parse_map(sprite["ascii_map"], w, h, name)
    out = bytearray()
    for line in rows:
        for ch in line:
            if ch == ".":
                out.extend((0, 0, 0, 0))
                continue
            if ch not in palette:
                raise ValueError(f"{name}: unknown palette char {ch!r}")
            out.extend(palette[ch])
    return bytes(out)


def lowest_opaque_row(w: int, h: int, rgba: bytes) -> int | None:
    last = None
    for y in range(h):
        for x in range(w):
            if rgba[(y * w + x) * 4 + 3] != 0:
                last = y
                break
    return last


def has_transparent(w: int, h: int, rgba: bytes) -> bool:
    for i in range(0, w * h * 4, 4):
        if rgba[i + 3] == 0:
            return True
    return False


def edges_match(w: int, h: int, rgba: bytes) -> tuple[bool, bool]:
    col_ok = True
    row_ok = True
    for y in range(h):
        a = rgba[(y * w + 0) * 4 : (y * w + 1) * 4]
        b = rgba[(y * w + (w - 1)) * 4 : (y * w + w) * 4]
        if a != b:
            col_ok = False
            break
    for x in range(w):
        a = rgba[(0 * w + x) * 4 : (0 * w + x + 1) * 4]
        b = rgba[((h - 1) * w + x) * 4 : ((h - 1) * w + x + 1) * 4]
        if a != b:
            row_ok = False
            break
    return col_ok, row_ok


# ---------------------------------------------------------------------------
# Contact sheet
# ---------------------------------------------------------------------------

_FONT_3X5 = {
    "a": (" # ", "# #", "###", "# #", "# #"),
    "b": ("## ", "# #", "## ", "# #", "## "),
    "c": (" ##", "#  ", "#  ", "#  ", " ##"),
    "d": ("## ", "# #", "# #", "# #", "## "),
    "e": ("###", "#  ", "## ", "#  ", "###"),
    "f": ("###", "#  ", "## ", "#  ", "#  "),
    "g": (" ##", "#  ", "# #", "# #", " ##"),
    "h": ("# #", "# #", "###", "# #", "# #"),
    "i": ("###", " # ", " # ", " # ", "###"),
    "k": ("# #", "# #", "## ", "# #", "# #"),
    "l": ("#  ", "#  ", "#  ", "#  ", "###"),
    "m": ("# #", "###", "# #", "# #", "# #"),
    "n": ("# #", "###", "###", "# #", "# #"),
    "o": (" # ", "# #", "# #", "# #", " # "),
    "p": ("## ", "# #", "## ", "#  ", "#  "),
    "r": ("## ", "# #", "## ", "# #", "# #"),
    "s": (" ##", "#  ", " # ", "  #", "## "),
    "t": ("###", " # ", " # ", " # ", " # "),
    "u": ("# #", "# #", "# #", "# #", "###"),
    "v": ("# #", "# #", "# #", "# #", " # "),
    "w": ("# #", "# #", "# #", "###", "# #"),
    "x": ("# #", "# #", " # ", "# #", "# #"),
    "y": ("# #", "# #", " # ", " # ", " # "),
    "_": ("   ", "   ", "   ", "   ", "###"),
    "-": ("   ", "   ", "###", "   ", "   "),
    "0": (" # ", "# #", "# #", "# #", " # "),
    "1": (" # ", "## ", " # ", " # ", "###"),
    "2": ("## ", "  #", " # ", "#  ", "###"),
}


def _blit(
    canvas: bytearray,
    cw: int,
    x0: int,
    y0: int,
    src_w: int,
    src_h: int,
    src: bytes,
    scale: int,
) -> None:
    for y in range(src_h):
        for x in range(src_w):
            i = (y * src_w + x) * 4
            r, g, b, a = src[i : i + 4]
            if a == 0:
                continue
            for dy in range(scale):
                for dx in range(scale):
                    px = x0 + x * scale + dx
                    py = y0 + y * scale + dy
                    j = (py * cw + px) * 4
                    canvas[j : j + 4] = bytes((r, g, b, 255))


def _draw_label(canvas: bytearray, cw: int, x0: int, y0: int, text: str) -> None:
    ink = (32, 32, 32, 255)
    x = x0
    for ch in text.lower():
        glyph = _FONT_3X5.get(ch)
        if glyph is None:
            x += 4
            continue
        for gy, row in enumerate(glyph):
            for gx, cell in enumerate(row):
                if cell == "#":
                    j = ((y0 + gy) * cw + (x + gx)) * 4
                    if 0 <= x + gx < cw:
                        canvas[j : j + 4] = bytes(ink)
        x += 4


def write_contact_sheet(rendered: list[tuple[dict, bytes]]) -> None:
    scale = 4
    cols = 8
    cell_w = 136
    cell_h = 148
    rows = (len(rendered) + cols - 1) // cols
    pad = 8
    cw = pad * 2 + cols * cell_w
    ch = pad * 2 + rows * cell_h
    bg = (128, 128, 128, 255)
    canvas = bytearray(bg * (cw * ch))
    for i, (sprite, rgba) in enumerate(rendered):
        col = i % cols
        row = i // cols
        x0 = pad + col * cell_w
        y0 = pad + row * cell_h
        sw, sh = sprite["w"], sprite["h"]
        # center the 4x sprite in the cell, leave room for the label
        px = x0 + (cell_w - sw * scale) // 2
        py = y0 + 4
        _blit(canvas, cw, px, py, sw, sh, rgba, scale)
        label = sprite["dest_name"].replace(".png", "")
        _draw_label(canvas, cw, x0 + 4, y0 + cell_h - 10, label[:16])
    write_png(CONTACT_PATH, cw, ch, bytes(canvas))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

CHAR_SPRITES = {
    "vela_idle.png",
    "vela_walk_a.png",
    "vela_walk_b.png",
    "vela_punch.png",
    "vela_crouch.png",
    "vela_hurt.png",
    "rook_idle.png",
    "rook_walk_a.png",
    "rook_walk_b.png",
    "rook_punch.png",
    "rook_crouch.png",
    "rook_hurt.png",
}

TILE_SPRITES = {
    "tile_floor.png",
    "tile_wall.png",
    "tile_plat.png",
    "ladder.png",
    "bg_panel.png",
}


def main() -> int:
    if [s["asset_id"] for s in SPRITES] != sorted(s["asset_id"] for s in SPRITES):
        raise SystemExit("asset ids must be listed in ascending order")
    if len(SPRITES) != 27:
        raise SystemExit(f"expected 27 sprites, got {len(SPRITES)}")

    ASSETS_DIR.mkdir(parents=True, exist_ok=True)
    rendered: list[tuple[dict, bytes]] = []
    print(f"{'path':<40} {'w':>4} {'h':>4} {'bytes':>8}")
    print("-" * 60)
    for sprite in SPRITES:
        rgba = rasterise(sprite)
        dest = ASSETS_DIR / sprite["dest_name"]
        write_png(dest, sprite["w"], sprite["h"], rgba)
        rendered.append((sprite, rgba))

    index = {
        "assets": [
            {"asset_id": s["asset_id"], "dest_rel": s["dest_rel"]} for s in SPRITES
        ]
    }
    INDEX_PATH.write_text(json.dumps(index, separators=(",", ":")) + "\n", encoding="utf-8")

    # verify on-disk
    print()
    print("ON-DISK VERIFY")
    print(f"{'path':<40} {'w':>4} {'h':>4} {'bytes':>8}")
    print("-" * 60)
    for sprite in SPRITES:
        dest = ASSETS_DIR / sprite["dest_name"]
        raw = dest.read_bytes()
        if raw[:8] != PNG_MAGIC:
            raise SystemExit(f"{dest} missing PNG magic")
        w, h, pixels = read_png(dest)
        if (w, h) != (sprite["w"], sprite["h"]):
            raise SystemExit(f"{dest} size {w}x{h} != {sprite['w']}x{sprite['h']}")
        rel = dest.relative_to(REPO_ROOT).as_posix()
        print(f"{rel:<40} {w:>4} {h:>4} {len(raw):>8}")

    print()
    print("TILING (col0==col w-1, row0==row h-1)")
    for name in (
        "tile_floor.png",
        "tile_wall.png",
        "tile_plat.png",
        "ladder.png",
        "bg_panel.png",
    ):
        dest = ASSETS_DIR / name
        w, h, pixels = read_png(dest)
        col_ok, row_ok = edges_match(w, h, pixels)
        print(f"  {name:<18} left-right={'OK' if col_ok else 'FAIL'}  top-bottom={'OK' if row_ok else 'FAIL'}")
        if not (col_ok and row_ok):
            raise SystemExit(f"{name} is not seamless")

    print()
    print("CHARACTER ALPHA / FEET")
    for sprite, rgba in rendered:
        if sprite["dest_name"] not in CHAR_SPRITES:
            continue
        w, h = sprite["w"], sprite["h"]
        trans = has_transparent(w, h, rgba)
        low = lowest_opaque_row(w, h, rgba)
        feet = low == h - 1
        print(
            f"  {sprite['dest_name']:<18} transparent={'OK' if trans else 'FAIL'}  "
            f"lowest_opaque={low}  feet={'OK' if feet else 'FAIL'}"
        )
        if not trans or not feet:
            raise SystemExit(f"{sprite['dest_name']} failed character checks")

    write_contact_sheet(rendered)
    print()
    print(f"wrote {INDEX_PATH.relative_to(REPO_ROOT).as_posix()}")
    print(f"wrote {CONTACT_PATH.relative_to(REPO_ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
